[package]
name = "openmw-settings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
peeking_take_while = "1.0.0"

# for build.rs
[dev-dependencies]
reqwest = { version = "0.12.4", features = ["blocking"] }
rstest = "0.21.0"
